branches:
  - master
  - +([0-9])?(.{+([0-9]),x}).x
  - name: next
    prerelease: true

plugins:
  - path: "@semantic-release/github"
  - path: "@semantic-release/git"
    assets:
      - CHANGELOG.md
      - ./artifacts/publish/**
