pool:
  name: kubernetes-agents

workspace:
  clean: all

trigger:
- master

variables:
- name: condo.target
  value: publish

resources:
  repositories:
  - repository: condo
    type: github
    endpoint: GitHub
    name: automotiveMastermind/condo
    ref: refs/heads/develop

steps:
- template: .azure/cli.yaml@condo
